name: campus_market
description: "Campus Market - A modern student marketplace Flutter application"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.1
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  confetti: ^0.7.0
  image: ^4.5.4

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  share_plus: ^12.0.0
  super_clipboard: ^0.9.1
  clipboard: ^2.0.2
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  geolocator: ^12.0.0

  # Database & API
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  golden_toolkit: ^0.15.0

  # notifications
  firebase_messaging: ^16.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
