// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDacVR49IYKM5NUgP6PlchNAH02Je9AhRk',
    appId: '1:984032807399:web:50e0cdc71b62aec99d1542',
    messagingSenderId: '984032807399',
    projectId: 'universestay-8c0e4',
    authDomain: 'universestay-8c0e4.firebaseapp.com',
    databaseURL: 'https://universestay-8c0e4-default-rtdb.firebaseio.com',
    storageBucket: 'universestay-8c0e4.appspot.com',
    measurementId: 'G-6RYNDDKK5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdNzHVzc_Mp9MNhhIxAVaZW4gQ-4AlGxQ',
    appId: '1:984032807399:android:5341b773819612329d1542',
    messagingSenderId: '984032807399',
    projectId: 'universestay-8c0e4',
    databaseURL: 'https://universestay-8c0e4-default-rtdb.firebaseio.com',
    storageBucket: 'universestay-8c0e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMCUBa8b8QJHiOR0t2IWLyzk2F-JG4n0',
    appId: '1:984032807399:ios:eed420986913c0e29d1542',
    messagingSenderId: '984032807399',
    projectId: 'universestay-8c0e4',
    databaseURL: 'https://universestay-8c0e4-default-rtdb.firebaseio.com',
    storageBucket: 'universestay-8c0e4.appspot.com',
    iosClientId: '984032807399-osklqevi75lbmj42hko2upllq27hi68n.apps.googleusercontent.com',
    iosBundleId: 'co.zw.appixia.campusmarket.campusMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMCUBa8b8QJHiOR0t2IWLyzk2F-JG4n0',
    appId: '1:984032807399:ios:eed420986913c0e29d1542',
    messagingSenderId: '984032807399',
    projectId: 'universestay-8c0e4',
    databaseURL: 'https://universestay-8c0e4-default-rtdb.firebaseio.com',
    storageBucket: 'universestay-8c0e4.appspot.com',
    iosClientId: '984032807399-osklqevi75lbmj42hko2upllq27hi68n.apps.googleusercontent.com',
    iosBundleId: 'co.zw.appixia.campusmarket.campusMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDacVR49IYKM5NUgP6PlchNAH02Je9AhRk',
    appId: '1:984032807399:web:d0e8e235c6dccca19d1542',
    messagingSenderId: '984032807399',
    projectId: 'universestay-8c0e4',
    authDomain: 'universestay-8c0e4.firebaseapp.com',
    databaseURL: 'https://universestay-8c0e4-default-rtdb.firebaseio.com',
    storageBucket: 'universestay-8c0e4.appspot.com',
    measurementId: 'G-V8JXVMZDK5',
  );

}